version: '3.8'

services:
  connections:
    build: .
    container_name: connections
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    command: npm run preview -- --host 0.0.0.0 --port 3002
    networks:
      - internal

networks:
  internal:
    external: true
    name: streaming_internal